# -*- coding: utf-8 -*-
"""Koreanize overlay UI by replacing exact quoted C string literals only."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent / "engine" / "sunone_aimbot_2" / "overlay"

# Map: English content inside quotes -> Korean (no quotes in keys/values)
PAIRS = [
    ("Frame source, monitor/window selection and preview.", "프레임 소스, 모니터/창 선택 및 미리보기."),
    ("Model, backend and detector thresholds.", "모델, 백엔드 및 탐지 임계값."),
    ("Depth inference, masks and depth debug overlay.", "깊이 추론, 마스크 및 깊이 디버그 오버레이."),
    ("Target selection and aim point offsets.", "타겟 선택 및 조준점 오프셋."),
    ("Current target identity lock status.", "현재 타겟 잠금 상태."),
    ("FOV, speed, target correction and motion profile.", "FOV, 속도, 타겟 보정 및 모션 프로필."),
    ("Prediction points and Kalman filter tuning.", "예측 포인트 및 칼만 필터 조정."),
    ("Auto shoot, recoil compensation and assist toggles.", "자동 사격, 반동 보정 및 보조 옵션."),
    ("Per-game sensitivity and profile management.", "게임별 감도 및 프로필 관리."),
    ("Mouse backend, device connection and reconnect data.", "마우스 백엔드, 장치 연결 및 재연결."),
    ("Bindings for aiming, shooting and runtime actions.", "조준·사격·런타임 동작 단축키."),
    ("Overlay appearance and privacy options.", "오버레이 모양 및 프라이버시 옵션."),
    ("In-game overlay lifetime, FPS and render toggles.", "인게임 오버레이 FPS 및 렌더 옵션."),
    ("Boxes, capture frame and future point styling.", "박스, 캡처 프레임 및 예측점 스타일."),
    ("Per-target icon image, size, anchor and class filter.", "타겟별 아이콘 이미지, 크기, 앵커, 클래스."),
    ("Performance, capture source and timing graphs.", "성능, 캡처 소스 및 타이밍 그래프."),
    ("Screenshots, data collection and diagnostics.", "스크린샷, 데이터 수집 및 진단."),
    ("AI Model", "AI 모델"),
    ("Input Device", "입력 장치"),
    ("Game Render", "게임 렌더"),
    ("Render Style", "렌더 스타일"),
    ("Icon Overlay", "아이콘 오버레이"),
    ("Capture", "캡처"),
    ("Depth", "깊이"),
    ("Target", "타겟"),
    ("Tracker", "트래커"),
    ("Movement", "이동"),
    ("Prediction", "예측"),
    ("Assist", "보조"),
    ("Profiles", "프로필"),
    ("Hotkeys", "단축키"),
    ("Overlay", "오버레이"),
    ("Stats", "통계"),
    ("Debug", "디버그"),
    ("Vision", "비전"),
    ("Aim", "조준"),
    ("Control", "조작"),
    ("Visuals", "비주얼"),
    ("Monitor", "모니터"),
    ("Depth preview appears in game overlay when debug overlay is enabled.", "디버그 오버레이가 켜져 있으면 게임 오버레이에 깊이 미리보기가 표시됩니다."),
    ("Enable Icon Overlay to edit settings.", "아이콘 오버레이를 켠 뒤에 설정을 편집할 수 있습니다."),
    ("Depth requires a CUDA build.", "깊이는 CUDA 빌드가 필요합니다."),
    ("Depth mask is disabled.", "깊이 마스크가 꺼져 있습니다."),
    ("Depth inference is disabled.", "깊이 추론이 꺼져 있습니다."),
    ("No models available in the 'models' folder.", "'models' 폴더에 사용 가능한 모델이 없습니다."),
    ("Fixed model size: Enabled", "고정 모델 크기: 켜짐"),
    ("Fixed model size: Disabled", "고정 모델 크기: 꺼짐"),
    ("TensorRT engine export", "TensorRT 엔진 내보내기"),
    ("Compiling optimized AI inference engine", "최적화된 AI 추론 엔진 컴파일 중"),
    ("Cancel export", "내보내기 취소"),
    ("Capture FPS cap is disabled.", "캡처 FPS 제한이 꺼져 있습니다."),
    ("WARNING: High FPS can reduce performance.", "경고: FPS가 높으면 성능이 떨어질 수 있습니다."),
    ("Available only with duplication_api.", "duplication_api에서만 사용할 수 있습니다."),
    ("No matching windows", "일치하는 창 없음"),
    ("No matching virtual cameras", "일치하는 가상 카메라 없음"),
    ("Apply UDP Settings", "UDP 설정 적용"),
    ("Use CUDA Direct Capture", "CUDA 직접 캡처 사용"),
    ("Detection Resolution", "탐지 해상도"),
    ("Capture FPS", "캡처 FPS"),
    ("Circle FOV size", "원형 FOV 크기"),
    ("Circle FOV", "원형 FOV"),
    ("Capture method", "캡처 방식"),
    ("Capture target (WinRT)", "캡처 대상 (WinRT)"),
    ("Window filter", "창 필터"),
    ("Window list", "창 목록"),
    ("Capture Borders", "창 테두리 포함"),
    ("Capture Cursor", "커서 포함"),
    ("Capture monitor", "캡처 모니터"),
    ("Virtual camera width", "가상 카메라 너비"),
    ("Virtual camera height", "가상 카메라 높이"),
    ("Virtual camera", "가상 카메라"),
    ("Camera list", "카메라 목록"),
    ("UDP settings", "UDP 설정"),
    ("UDP IP", "UDP IP"),
    ("UDP Port", "UDP 포트"),
    ("General Capture", "일반 캡처"),
    ("Monitor Capture", "모니터 캡처"),
    ("Virtual Camera", "가상 카메라"),
    ("UDP Capture", "UDP 캡처"),
    ("Confidence Threshold", "탐지 신뢰도"),
    ("NMS Threshold", "NMS 임계값"),
    ("Max Detections", "최대 탐지 수"),
    ("Disable Headshot", "헤드샷 끄기"),
    ("Auto Aim", "자동 조준"),
    ("Approximate Body Y Offset", "몸 Y 오프셋 (대략)"),
    ("Approximate Head Y Offset", "머리 Y 오프셋 (대략)"),
    ("Enable Tracker", "트래커 사용"),
    ("Show Target Table", "타겟 표 표시"),
    ("Image not found!", "이미지를 찾을 수 없습니다!"),
    ("Note: There is a different value for each game, as the sizes of the player models may vary.", "참고: 게임마다 플레이어 모델 크기가 달라 값이 다를 수 있습니다."),
    ("Mode: Simple Lock", "모드: 단순 잠금"),
    ("No active tracks", "활성 트랙 없음"),
    ("Min Speed Multiplier", "최소 속도 배율"),
    ("Max Speed Multiplier", "최대 속도 배율"),
    ("Prediction Interval", "예측 간격"),
    ("Future Positions", "미래 위치 수"),
    ("Draw Future Positions", "미래 위치 그리기"),
    ("Enable Kalman Filter", "칼만 필터 사용"),
    ("Kalman Process Noise Pos", "칼만 프로세스 노이즈 (위치)"),
    ("Kalman Process Noise Vel", "칼만 프로세스 노이즈 (속도)"),
    ("Kalman Measurement Noise", "칼만 측정 노이즈"),
    ("Kalman Velocity Damping", "칼만 속도 감쇠"),
    ("Kalman Max Velocity", "칼만 최대 속도"),
    ("Kalman Warmup Frames", "칼만 워밍업 프레임"),
    ("Kalman Compensate Inference Delay", "칼만 추론 지연 보정"),
    ("Kalman Additional Predict (ms)", "칼만 추가 예측 (ms)"),
    ("Kalman Reset Timeout (s)", "칼만 리셋 타임아웃 (초)"),
    ("Snap Radius", "스냅 반경"),
    ("Near Radius", "근접 반경"),
    ("Speed Curve Exponent", "속도 곡선 지수"),
    ("Snap Boost Factor", "스냅 부스트"),
    ("Active Game Profile", "활성 게임 프로필"),
    ("New profile name", "새 프로필 이름"),
    ("FOV Scaled", "FOV 스케일"),
    ("Base FOV", "기본 FOV"),
    ("Delete Current Profile", "현재 프로필 삭제"),
    ("Easy No Recoil", "간편 반동 보정"),
    ("No Recoil Strength", "반동 보정 강도"),
    ("Auto Shoot", "자동 사격"),
    ("bScope Multiplier", "스코프 배율"),
    ("Enable WindMouse", "WindMouse 사용"),
    ("Gravity force", "중력"),
    ("Wind fluctuation", "바람 변동"),
    ("Max step (velocity clip)", "최대 스텝 (속도 제한)"),
    ("Distance where behaviour changes", "동작 전환 거리"),
    ("Reset to defaults", "기본값으로 초기화"),
    ("Mouse Input Method", "마우스 입력 방식"),
    ("Arduino 16-bit Mouse", "아두이노 16비트 마우스"),
    ("Arduino Enable Keys", "아두이노 키 사용"),
    ("RP2350 16-bit Mouse", "RP2350 16비트 마우스"),
    ("RP2350 Enable Keys", "RP2350 키 사용"),
    ("Makcu Enable Keys", "Makcu 키 사용"),
    ("Open GHub Docs", "GHub 문서 열기"),
    ("Save & Reconnect", "저장 및 재연결"),
    ("Arrow Key Options", "방향키 옵션"),
    ("Reload Config", "설정 리로드"),
    ("Open Overlay", "오버레이 열기"),
    ("No key list available.", "사용 가능한 키 목록이 없습니다."),
    ("Overlay Opacity", "오버레이 불투명도"),
    ("UI Fine Scale", "UI 배율"),
    ("Hide Overlays From Recording", "녹화에서 오버레이 숨기기"),
    ("Overlay Max FPS (0 = uncapped)", "오버레이 최대 FPS (0=무제한)"),
    ("Draw Detection Boxes", "탐지 박스 그리기"),
    ("Compensate Overlay Latency", "오버레이 지연 보정"),
    ("Draw Wind Debug Tail", "Wind 디버그 꼬리 그리기"),
    ("Show Target Correction", "타겟 보정 표시"),
    ("Box Thickness", "박스 두께"),
    ("Draw Capture Frame", "캡처 프레임 그리기"),
    ("Draw Circle Guide", "원형 가이드 그리기"),
    ("Frame Thickness", "프레임 두께"),
    ("Point Radius", "점 반경"),
    ("Point Step Alpha Falloff", "점 알파 감쇠"),
    ("Enable Icon Overlay", "아이콘 오버레이 사용"),
    ("Icon Path", "아이콘 경로"),
    ("Icon Width", "아이콘 너비"),
    ("Icon Height", "아이콘 높이"),
    ("Icon Offset X", "아이콘 X 오프셋"),
    ("Icon Offset Y", "아이콘 Y 오프셋"),
    ("Icon Class (-1 = all)", "아이콘 클래스 (-1=전체)"),
    ("Icon Anchor", "아이콘 앵커"),
    ("Collect data while playing", "플레이 중 데이터 수집"),
    ("Only when aimbot is active", "에임봇 활성 시에만"),
    ("Only when targets exist", "타겟이 있을 때만"),
    ("Save every N frames", "N프레임마다 저장"),
    ("JPEG quality", "JPEG 품질"),
    ("Output folder", "출력 폴더"),
    ("Write YOLO txt labels", "YOLO txt 라벨 저장"),
    ("Min confidence", "최소 신뢰도"),
    ("Max boxes per file", "파일당 최대 박스"),
    ("Class filter", "클래스 필터"),
    ("Copy path", "경로 복사"),
    ("Reset counters", "카운터 초기화"),
    ("Debug scale", "디버그 배율"),
    ("Show Preview Window", "미리보기 창 표시"),
    ("Screenshot delay", "스크린샷 지연"),
    ("Verbose console output", "상세 콘솔 출력"),
    ("Print build information", "빌드 정보 출력"),
    ("Data Collection", "데이터 수집"),
    ("Auto Label", "자동 라벨"),
    ("Capture Preview", "캡처 미리보기"),
    ("Screenshot Buttons", "스크린샷 버튼"),
    ("Enable Depth Inference", "깊이 추론 사용"),
    ("Depth model", "깊이 모델"),
    ("Load depth model", "깊이 모델 로드"),
    ("Export depth engine", "깊이 엔진 내보내기"),
    ("Depth Mask FPS", "깊이 마스크 FPS"),
    ("Depth FPS", "깊이 FPS"),
    ("Enable Depth Mask", "깊이 마스크 사용"),
    ("Depth Mask Near %", "깊이 마스크 Near %"),
    ("Depth Mask Expand (px)", "깊이 마스크 확장 (px)"),
    ("Depth Mask Hold Frames", "깊이 마스크 유지 프레임"),
    ("Depth Mask Alpha", "깊이 마스크 알파"),
    ("Depth Mask Invert", "깊이 마스크 반전"),
    ("Depth Debug Overlay (Game)", "깊이 디버그 오버레이 (게임)"),
    ("Depth colormap", "깊이 컬러맵"),
    ("Depth Inference", "깊이 추론"),
    ("Depth Runtime", "깊이 런타임"),
    ("Depth Mask", "깊이 마스크"),
    ("Depth Status", "깊이 상태"),
    ("Time Breakdown", "시간 분석"),
    ("Capture Details", "캡처 상세"),
    ("Manage Profiles", "프로필 관리"),
    ("Game Profile", "게임 프로필"),
    ("Target correction", "타겟 보정"),
    ("Speed Multiplier", "속도 배율"),
    ("Input Method", "입력 방식"),
    ("Wind Mouse", "Wind Mouse"),
    ("Box Color", "박스 색"),
    ("Capture Frame", "캡처 프레임"),
    ("Future Point Style", "미래 점 스타일"),
    ("Building optimized engine", "최적화된 엔진 빌드 중"),
    ("Overall progress", "전체 진행"),
    ("TensorRT may spend a long time selecting tactics without reporting new steps.", "TensorRT가 새 단계 보고 없이 전술 선택에 오래 걸릴 수 있습니다."),
    ("Waiting for TensorRT to report build phases", "TensorRT 빌드 단계 보고 대기 중"),
    ("Leave class filter empty to record all classes. Use comma-separated ids like 0,1.", "클래스 필터를 비우면 모든 클래스를 기록합니다. 예: 0,1"),
    ("Enable Easy No Recoil to edit settings.", "간편 반동 보정을 켠 뒤 설정을 편집하세요."),
    ("Enable Auto Shoot to edit settings.", "자동 사격을 켠 뒤 설정을 편집하세요."),
    ("Enable WindMouse to edit settings.", "WindMouse를 켠 뒤 설정을 편집하세요."),
    ("Prediction is disabled.", "예측이 꺼져 있습니다."),
    ("Enable Prediction Interval (> 0) to edit this section.", "예측 간격을 0보다 크게 설정해야 이 섹션을 편집할 수 있습니다."),
    ("WARNING: High recoil strength may be detected.", "경고: 반동 보정 강도가 높으면 감지될 수 있습니다."),
    ("This is a standard mouse input method, it may not work in most games. Use GHUB, RAZER, ARDUINO, RP2350, TEENSY41, or TEENSY41_HID.", "표준 마우스 입력입니다. 많은 게임에서 동작하지 않을 수 있습니다. GHUB, RAZER, ARDUINO, RP2350, TEENSY41, TEENSY41_HID를 사용하세요."),
    ("Requires rzctl.dll next to ai.exe.", "ai.exe와 같은 폴더에 rzctl.dll이 필요합니다."),
    ("Use at your own risk, the method is detected in some games.", "일부 게임에서 감지될 수 있습니다. 사용은 본인 책임입니다."),
    ("Refresh", "새로고침"),
    ("Browse", "찾아보기"),
    ("Export", "내보내기"),
    ("Enable", "사용"),
    ("Filter", "필터"),
    ("Window", "창"),
    ("Model", "모델"),
    ("Detection", "탐지"),
    ("Targeting", "조준"),
    ("Offsets", "오프셋"),
    ("Preview", "미리보기"),
    ("Status", "상태"),
    ("Tracks", "트랙"),
    ("Visual", "비주얼"),
    ("General", "일반"),
    ("Errors", "오류"),
    ("Shoot", "사격"),
    ("Zoom", "줌"),
    ("Exit", "종료"),
    ("Pause", "일시정지"),
    ("Load", "로드"),
    ("Add", "추가"),
    ("Sensitivity", "감도"),
    ("Alpha", "알파"),
    ("Red", "빨강"),
    ("Green", "초록"),
    ("Blue", "파랑"),
    ("Screenshot", "스크린샷"),
    ("Body", "몸"),
    ("Head", "머리"),
    ("Yes", "예"),
    ("No", "아니오"),
    ("None", "없음"),
    ("Canceling", "취소 중"),
    ("Working", "작업 중"),
    ("Running", "실행 중"),
    ("Preparing", "준비 중"),
    ("Preprocess", "전처리"),
    ("Inference", "추론"),
    ("Postprocess", "후처리"),
    ("Copy", "복사"),
    ("FOV X", "FOV X"),
    ("FOV Y", "FOV Y"),
    ("Yaw", "Yaw"),
    ("Pitch", "Pitch"),
]

# Skip files where short quoted strings would break APIs
SKIP = {"Game_overlay.h", "Game_overlay.cpp", "config_dirty.h", "config_dirty.cpp", "overlay.h"}

ICON_GROUP_FIXES = [
    ('std::strcmp(group, "Vision")', 'std::strcmp(group, "비전")'),
    ('std::strcmp(group, "Aim")', 'std::strcmp(group, "조준")'),
    ('std::strcmp(group, "Control")', 'std::strcmp(group, "조작")'),
    ('std::strcmp(group, "Visuals")', 'std::strcmp(group, "비주얼")'),
]


def q(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    # longest first
    pairs = sorted(PAIRS, key=lambda x: len(x[0]), reverse=True)
    files = [p for p in list(ROOT.glob("*.cpp")) + list(ROOT.glob("*.h")) if p.name not in SKIP]
    total = 0
    for path in files:
        text = path.read_text(encoding="utf-8")
        orig = text
        for en, ko in pairs:
            text = text.replace(q(en), q(ko))
        if path.name == "overlay.cpp":
            for a, b in ICON_GROUP_FIXES:
                text = text.replace(a, b)
        if text != orig:
            path.write_text(text, encoding="utf-8")
            print("updated", path.name)
            total += 1
    print("done", total, "files")


if __name__ == "__main__":
    main()
